# Deployment for Data Analysis
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: twitter-data
      component: analysis
  template:
    metadata:
      labels:
        app: twitter-data
        component: analysis
    spec:
      containers:
      - name: analysis
        image: thisguygil/twitter-data-analysis
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: "200m"
            memory: "400Mi"
          limits:
            cpu: "500m"
            memory: "800Mi"
      imagePullSecrets:
      - name: my-docker-hub-secret
---
# Deployment for Front-end Web UI
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: twitter-data
      component: frontend
  template:
    metadata:
      labels:
        app: twitter-data
        component: frontend
    spec:
      containers:
      - name: frontend
        image: thisguygil/twitter-data-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
      imagePullSecrets:
      - name: my-docker-hub-secret
---
# Deployment for MySQL Database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
# Persistent Volume for MySQL Database
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
