apiVersion: batch/v1
kind: Job
metadata:
  name: ingestion-job
spec:
  template:
    spec:
      containers:
      - name: ingestion
        image: thisguygil/twitter-data-ingestion
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
      restartPolicy: Never
  backoffLimit: 0
